image: alpine/latest
packages:
- npm
- rsync
sources:
- https://git.sr.ht/~emersion/gamja
secrets:
- 5874ac5a-905e-4596-a117-fed1401c60ce # deploy SSH key
tasks:
- setup: |
    cd gamja
    npm install --include=dev
    npm run build
- deploy: |
    cd gamja/dist
    [ "$(git rev-parse HEAD)" = "$(git rev-parse origin/master)" ] || complete-build
    rsync --rsh="ssh -o StrictHostKeyChecking=no" -rP \
      --delete --exclude=config.json \
      . deploy@emersion.fr:/srv/http/gamja
