image: alpine/latest
packages:
- npm
- rsync
sources:
- https://git.sr.ht/~emersion/gamja
secrets:
- 77c7956b-003e-44f7-bb5c-2944b2047654 # deploy SSH key
tasks:
- setup: |
    cd gamja
    npm install --include=dev
    npm run build
- deploy: |
    cd gamja/dist
    [ "$(git rev-parse HEAD)" = "$(git rev-parse origin/master)" ] || complete-build
    rsync --rsh="ssh -o StrictHostKeyChecking=no" -rP \
      --delete --exclude=config.json \
      . deploy@sheeta.emersion.fr:/srv/http/gamja
